interface ProjectsI {
  title: string;
  subtitle: string;
  client: string;
  area: string;
  value: string;
  location: string;
  year: number;
  architect: string;
  link: string;
  imgSrc: string;
}

export interface ProjectCategoriesI {
  isActive: boolean;
  text: string;
}

export const projects: ProjectsI[] = [
  {
    title: "It has roots in a piece of side dormen diall",
    subtitle: "Lorem ipsum damal solar",
    client: "A Big Company",
    area: "100,000 m2",
    value: "$150.000",
    location: "Montevideo, Uruguay",
    year: 2021,
    architect: "Jack Deripper",
    link: "/projects/item",
    content: "Lorem ipsum dolor sit amet, conse nil adipiscing Donec nec eros trist ms pellentesqu no liues il Ut et con gue augue Maecenas feec eros tristiq nsllla pellent Ut et co augue Maecenas fermentum vel ante a aliqi. Etiam vivas sapien. vel ante a aliq tristiq eget Lorem ipsum dolor sit amet, conse n pellentesqu no liues il Ut et congue augue. Maecenas feec eros tristiq nsl lla pellent Ut et co augue Maecenas fermentum vel Maecenas fermentum vel anteante.",
    list: ['Lorem ipsum dolor', 'Sir samet salar dall', 'Matroska del monor'],
    imgSrc: "../assets/construction-project-1.png",
  },
  {
    title: "Madri cal alaa roots in a piece of side",
    subtitle: "Lorem ipsum damal",
    client: "A Big Company",
    area: "100,000 m2",
    value: "$150.000",
    location: "Montevideo, Uruguay",
    year: 2021,
    architect: "Jack Deripper",
    link: "/projects/item",
    content: "Lorem ipsum dolor sit amet, conse nil adipiscing Donec nec eros trist ms pellentesqu no liues il Ut et con gue augue Maecenas feec eros tristiq nsllla pellent Ut et co augue Maecenas fermentum vel ante a aliqi. Etiam vivas sapien. vel ante a aliq tristiq eget Lorem ipsum dolor sit amet, conse n pellentesqu no liues il Ut et congue augue. Maecenas feec eros tristiq nsl lla pellent Ut et co augue Maecenas fermentum vel Maecenas fermentum vel anteante.",
    list: ['Lorem ipsum dolor', 'Sir samet salar dall', 'Matroska del monor'],
    imgSrc: "../assets/construction-project-2.png",
  },
  {
    title: "Lorem ipsum dolor sit amet doll dell",
    subtitle: "Lorem ipsum damal",
    client: "A Big Company",
    area: "100,000 m2",
    value: "$150.000",
    location: "Montevideo, Uruguay",
    year: 2021,
    architect: "Jack Deripper",
    link: "/projects/item",
    content: "Lorem ipsum dolor sit amet, conse nil adipiscing Donec nec eros trist ms pellentesqu no liues il Ut et con gue augue Maecenas feec eros tristiq nsllla pellent Ut et co augue Maecenas fermentum vel ante a aliqi. Etiam vivas sapien. vel ante a aliq tristiq eget Lorem ipsum dolor sit amet, conse n pellentesqu no liues il Ut et congue augue. Maecenas feec eros tristiq nsl lla pellent Ut et co augue Maecenas fermentum vel Maecenas fermentum vel anteante.",
    list: ['Lorem ipsum dolor', 'Sir samet salar dall', 'Matroska del monor'],
    imgSrc: "../assets/construction-project-3.png",
  },
  {
    title: "Build The House Of Your Dreams",
    subtitle: "Lorem ipsum damal",
    client: "A Big Company",
    area: "100,000 m2",
    value: "$150.000",
    location: "Montevideo, Uruguay",
    year: 2021,
    architect: "Jack Deripper",
    link: "/projects/item",
    content: "Lorem ipsum dolor sit amet, conse nil adipiscing Donec nec eros trist ms pellentesqu no liues il Ut et con gue augue Maecenas feec eros tristiq nsllla pellent Ut et co augue Maecenas fermentum vel ante a aliqi. Etiam vivas sapien. vel ante a aliq tristiq eget Lorem ipsum dolor sit amet, conse n pellentesqu no liues il Ut et congue augue. Maecenas feec eros tristiq nsl lla pellent Ut et co augue Maecenas fermentum vel Maecenas fermentum vel anteante.",
    list: ['Lorem ipsum dolor', 'Sir samet salar dall', 'Matroska del monor'],
    imgSrc: "../assets/construction-project-4.png",
  },
  {
    title: "Sapien nec ante sollicitudin",
    subtitle: "Lorem ipsum damal",
    client: "A Big Company",
    area: "100,000 m2",
    value: "$150.000",
    location: "Montevideo, Uruguay",
    year: 2021,
    architect: "Jack Deripper",
    link: "/projects/item",
    content: "Lorem ipsum dolor sit amet, conse nil adipiscing Donec nec eros trist ms pellentesqu no liues il Ut et con gue augue Maecenas feec eros tristiq nsllla pellent Ut et co augue Maecenas fermentum vel ante a aliqi. Etiam vivas sapien. vel ante a aliq tristiq eget Lorem ipsum dolor sit amet, conse n pellentesqu no liues il Ut et congue augue. Maecenas feec eros tristiq nsl lla pellent Ut et co augue Maecenas fermentum vel Maecenas fermentum vel anteante.",
    list: ['Lorem ipsum dolor', 'Sir samet salar dall', 'Matroska del monor'],
    imgSrc: "../assets/construction-project-5.png",
  },
  {
    title: "Lorem ipsum dolor",
    subtitle: "Lorem ipsum damal",
    client: "A Big Company",
    area: "100,000 m2",
    value: "$150.000",
    location: "Montevideo, Uruguay",
    year: 2021,
    architect: "Jack Deripper",
    link: "/projects/item",
    content: "Lorem ipsum dolor sit amet, conse nil adipiscing Donec nec eros trist ms pellentesqu no liues il Ut et con gue augue Maecenas feec eros tristiq nsllla pellent Ut et co augue Maecenas fermentum vel ante a aliqi. Etiam vivas sapien. vel ante a aliq tristiq eget Lorem ipsum dolor sit amet, conse n pellentesqu no liues il Ut et congue augue. Maecenas feec eros tristiq nsl lla pellent Ut et co augue Maecenas fermentum vel Maecenas fermentum vel anteante.",
    list: ['Lorem ipsum dolor', 'Sir samet salar dall', 'Matroska del monor'],
    imgSrc: "../assets/construction-project-6.png",
  },
  {
    title: "Ante sollicitudin luctus",
    subtitle: "Lorem ipsum damal",
    client: "A Big Company",
    area: "100,000 m2",
    value: "$150.000",
    location: "Montevideo, Uruguay",
    year: 2021,
    architect: "Jack Deripper",
    link: "/projects/item",
    content: "Lorem ipsum dolor sit amet, conse nil adipiscing Donec nec eros trist ms pellentesqu no liues il Ut et con gue augue Maecenas feec eros tristiq nsllla pellent Ut et co augue Maecenas fermentum vel ante a aliqi. Etiam vivas sapien. vel ante a aliq tristiq eget Lorem ipsum dolor sit amet, conse n pellentesqu no liues il Ut et congue augue. Maecenas feec eros tristiq nsl lla pellent Ut et co augue Maecenas fermentum vel Maecenas fermentum vel anteante.",
    list: ['Lorem ipsum dolor', 'Sir samet salar dall', 'Matroska del monor'],
    imgSrc: "../assets/construction-project-7.png",
  },
  {
    title: "Dolores dellano",
    subtitle: "Lorem ipsum damal",
    client: "A Big Company",
    area: "100,000 m2",
    value: "$150.000",
    location: "Montevideo, Uruguay",
    year: 2021,
    architect: "Jack Deripper",
    link: "/projects/item",
    content: "Lorem ipsum dolor sit amet, conse nil adipiscing Donec nec eros trist ms pellentesqu no liues il Ut et con gue augue Maecenas feec eros tristiq nsllla pellent Ut et co augue Maecenas fermentum vel ante a aliqi. Etiam vivas sapien. vel ante a aliq tristiq eget Lorem ipsum dolor sit amet, conse n pellentesqu no liues il Ut et congue augue. Maecenas feec eros tristiq nsl lla pellent Ut et co augue Maecenas fermentum vel Maecenas fermentum vel anteante.",
    list: ['Lorem ipsum dolor', 'Sir samet salar dall', 'Matroska del monor'],
    imgSrc: "../assets/construction-project-8.png",
  },
  {
    title: "Matrosko ver",
    subtitle: "Lorem ipsum damal",
    client: "A Big Company",
    area: "100,000 m2",
    value: "$150.000",
    location: "Montevideo, Uruguay",
    year: 2021,
    architect: "Jack Deripper",
    link: "/projects/item",
    content: "Lorem ipsum dolor sit amet, conse nil adipiscing Donec nec eros trist ms pellentesqu no liues il Ut et con gue augue Maecenas feec eros tristiq nsllla pellent Ut et co augue Maecenas fermentum vel ante a aliqi. Etiam vivas sapien. vel ante a aliq tristiq eget Lorem ipsum dolor sit amet, conse n pellentesqu no liues il Ut et congue augue. Maecenas feec eros tristiq nsl lla pellent Ut et co augue Maecenas fermentum vel Maecenas fermentum vel anteante.",
    list: ['Lorem ipsum dolor', 'Sir samet salar dall', 'Matroska del monor'],
    imgSrc: "../assets/construction-project-9.png",
  },
  {
    title: "Ante sollicitudin luctus",
    subtitle: "Lorem ipsum damal",
    client: "A Big Company",
    area: "100,000 m2",
    value: "$150.000",
    location: "Montevideo, Uruguay",
    year: 2021,
    architect: "Jack Deripper",
    link: "/projects/item",
    content: "Lorem ipsum dolor sit amet, conse nil adipiscing Donec nec eros trist ms pellentesqu no liues il Ut et con gue augue Maecenas feec eros tristiq nsllla pellent Ut et co augue Maecenas fermentum vel ante a aliqi. Etiam vivas sapien. vel ante a aliq tristiq eget Lorem ipsum dolor sit amet, conse n pellentesqu no liues il Ut et congue augue. Maecenas feec eros tristiq nsl lla pellent Ut et co augue Maecenas fermentum vel Maecenas fermentum vel anteante.",
    list: ['Lorem ipsum dolor', 'Sir samet salar dall', 'Matroska del monor'],
    imgSrc: "../assets/construction-project-1.png",
  },
  {
    title: "Matrosko ver",
    subtitle: "Lorem ipsum damal",
    client: "A Big Company",
    area: "100,000 m2",
    value: "$150.000",
    location: "Montevideo, Uruguay",
    year: 2021,
    architect: "Jack Deripper",
    link: "/projects/item",
    content: "Lorem ipsum dolor sit amet, conse nil adipiscing Donec nec eros trist ms pellentesqu no liues il Ut et con gue augue Maecenas feec eros tristiq nsllla pellent Ut et co augue Maecenas fermentum vel ante a aliqi. Etiam vivas sapien. vel ante a aliq tristiq eget Lorem ipsum dolor sit amet, conse n pellentesqu no liues il Ut et congue augue. Maecenas feec eros tristiq nsl lla pellent Ut et co augue Maecenas fermentum vel Maecenas fermentum vel anteante.",
    list: ['Lorem ipsum dolor', 'Sir samet salar dall', 'Matroska del monor'],
    imgSrc: "../assets/construction-project-2.png",
  },
  {
    title: "Ante sollicitudin luctus",
    subtitle: "Lorem ipsum damal",
    client: "A Big Company",
    area: "100,000 m2",
    value: "$150.000",
    location: "Montevideo, Uruguay",
    year: 2021,
    architect: "Jack Deripper",
    link: "/projects/item",
    content: "Lorem ipsum dolor sit amet, conse nil adipiscing Donec nec eros trist ms pellentesqu no liues il Ut et con gue augue Maecenas feec eros tristiq nsllla pellent Ut et co augue Maecenas fermentum vel ante a aliqi. Etiam vivas sapien. vel ante a aliq tristiq eget Lorem ipsum dolor sit amet, conse n pellentesqu no liues il Ut et congue augue. Maecenas feec eros tristiq nsl lla pellent Ut et co augue Maecenas fermentum vel Maecenas fermentum vel anteante.",
    list: ['Lorem ipsum dolor', 'Sir samet salar dall', 'Matroska del monor'],
    imgSrc: "../assets/construction-project-3.png",
  },
];

export const projectCategories: ProjectCategoriesI[] = [
  {
    isActive: true,
    text: "All",
  },
  {
    isActive: false,
    text: "Building",
  },
  {
    isActive: false,
    text: "Interior",
  },
  {
    isActive: false,
    text: "Design",
  },
  {
    isActive: false,
    text: "Plumbing",
  },
  {
    isActive: false,
    text: "Tilling",
  },
];
